### PR TITLE
Remove endpoints for proxying payload

### PR DESCRIPTION
**Pull request by xprazak2**
Contains #50 and #55 in a single branch for easier testing.

### CODE REVIEW

**Comment by ShimShtein** [comment]
Registered a host with this PR and everything worked as expected.

:+1:  from me.

**Comment by lphiri** [comment]
@ShimShtein did your test include checking that the host appears in the old plugin UI?

**Comment by ShimShtein** [comment]
@lphiri, thanks for pointing this out. This one behaves as expected, but its rh_cloud counterpart (https://github.com/theforeman/foreman_rh_cloud/pull/412) breaks the old plugin. I have left comments there.

**Comment by ShimShtein** [comment]
@lphiri, I have acked rh_cloud counterpart, it looks like now both plugins can coexist. Would you mind giving it a spin before I merge?

**Comment by lphiri** [comment]
@rexwhite - can you take a look please?

**Comment by rexwhite** [comment]
This all looks good, we just need to be mindful when packaging this change to require the appropriate corresponding changes to Foreman for each version of Satellite that gets this update.

**Comment by rexwhite** [comment]
I just published redhat_access-2.2.19.gem with this fix.

**Pull request merged**
