### PR TITLE
Fixes #47 - Use import for assets instead of require

### LINKED ISSUE #47: assets can't be compiled using sassc instead of rails-sass
v2.2.14 on rubygems (which I btw can't find here on github) fails to build the assets:

```
** Execute plugin:assets:precompile
I, [2020-05-20T12:19:57.564730 #14344]  INFO -- : Writing /builddir/build/BUILDROOT/tfm-rubygem-redhat_access-2.2.14-1.fm2_2.el7.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/redhat_access-2.2.14/public/assets/redhat_access/application-3383e1866cfbdaa4b47248bef36b577366dd1060687c5d66d3f042089c0656e4.js
I, [2020-05-20T12:19:57.565451 #14344]  INFO -- : Writing /builddir/build/BUILDROOT/tfm-rubygem-redhat_access-2.2.14-1.fm2_2.el7.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/redhat_access-2.2.14/public/assets/redhat_access/application-3383e1866cfbdaa4b47248bef36b577366dd1060687c5d66d3f042089c0656e4.js.gz
I, [2020-05-20T12:19:57.630443 #14344]  INFO -- : Writing /builddir/build/BUILDROOT/tfm-rubygem-redhat_access-2.2.14-1.fm2_2.el7.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/redhat_access-2.2.14/public/assets/redhat_access/application-162d17661e4a83772eed70ecf28b91a4928036b15af51c642c157ebce7fecf8d.css
I, [2020-05-20T12:19:57.630677 #14344]  INFO -- : Writing /builddir/build/BUILDROOT/tfm-rubygem-redhat_access-2.2.14-1.fm2_2.el7.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/redhat_access-2.2.14/public/assets/redhat_access/application-162d17661e4a83772eed70ecf28b91a4928036b15af51c642c157ebce7fecf8d.css.gz
I, [2020-05-20T12:20:21.905433 #14344]  INFO -- : Writing /builddir/build/BUILDROOT/tfm-rubygem-redhat_access-2.2.14-1.fm2_2.el7.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/redhat_access-2.2.14/public/assets/insights/application-54ffd616834e94110ad90f320379c6d285d4a38fe99a6ed35146dc41acc124d0.js
I, [2020-05-20T12:20:21.905649 #14344]  INFO -- : Writing /builddir/build/BUILDROOT/tfm-rubygem-redhat_access-2.2.14-1.fm2_2.el7.noarch/opt/theforeman/tfm/root/usr/share/gems/gems/redhat_access-2.2.14/public/assets/insights/application-54ffd616834e94110ad90f320379c6d285d4a38fe99a6ed35146dc41acc124d0.js.gz
rake aborted!
SassC::SyntaxError: Error: Invalid CSS after "...er{float:right}": expected 1 selector or at-rule, was ".error-info .md-chi"
        on line 25 of stdin
>> g-dirty,.md-chips .md-chip-input-container .error-info select[type=tel].change
   ------------------------------------------^
stdin:25
/opt/theforeman/tfm/root/usr/share/gems/gems/sassc-2.2.1/lib/sassc/engine.rb:49:in `render'
/opt/theforeman/tfm/root/usr/share/gems/gems/sassc-rails-2.1.2/lib/sassc/rails/compressor.rb:29:in `call'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/sass_compressor.rb:28:in `call'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:75:in `call_processor'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:57:in `block in call_processors'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `reverse_each'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/processor_utils.rb:56:in `call_processors'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:134:in `load_from_unloaded'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:60:in `block in load'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:317:in `fetch_asset_from_dependency_cache'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/loader.rb:44:in `load'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:20:in `block in initialize'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/cached_environment.rb:47:in `load'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/base.rb:66:in `find_asset'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/base.rb:73:in `find_all_linked_assets'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:134:in `block in find'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `each'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:133:in `find'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/sprockets/manifest.rb:186:in `compile'
/builddir/build/BUILD/redhat_access-2.2.14/usr/share/foreman/lib/tasks/plugin_assets.rake:24:in `block in compile'
/opt/theforeman/tfm/root/usr/share/gems/gems/sprockets-3.7.2/lib/rake/sprocketstask.rb:147:in `with_logger'
/builddir/build/BUILD/redhat_access-2.2.14/usr/share/foreman/lib/tasks/plugin_assets.rake:23:in `compile'
/builddir/build/BUILD/redhat_access-2.2.14/usr/share/foreman/lib/tasks/plugin_assets.rake:63:in `block in <top (required)>'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/opt/rh/rh-ruby25/root/usr/share/ruby/monitor.rb:226:in `mon_synchronize'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/opt/rh/rh-ruby25/root/usr/share/gems/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/opt/rh/rh-ruby25/root/usr/bin/rake:23:in `load'
/opt/rh/rh-ruby25/root/usr/bin/rake:23:in `<main>'
Tasks: TOP => plugin:assets:precompile
```

### PR DESCRIPTION
**Pull request by ehelms**

### CODE REVIEW

**Comment by ShimShtein** [comment]
Doesn't `@include` require webpack? I think it won't compile with older assets model.

**Comment by ehelms** [comment]
The @import is an SCSS construct that can be used here. You can check the blurb in this section -- https://guides.rubyonrails.org/asset_pipeline.html#manifest-files-and-directives

As soon as an updated build of Katello goes through, you'll be able to see this patch working over here -- https://github.com/theforeman/foreman-packaging/pull/5749

**Comment by ehelms** [comment]
@ShimShtein If you can take a look at the referenced PR for packaging that shows it now builds correctly. If you want to take it for a spin you can install the scratch RPM. Effectively, all new builds of this plugin are blocked on this issue.

**Comment by ShimShtein** [comment]
@rexwhite, I'm OK with this change. leaving this to up to you to check if the css is applied correctly.

**Review by rexwhite — APPROVED** [review]
I believe this should be fine.

**Comment by ehelms** [comment]
Thanks! @rexwhite when might we expect a release with this fix in it?

**Comment by rexwhite** [comment]
I published redhat_access-2.2.17.gem with these changes about 2 minutes ago :-)

**Pull request merged**
